// villagerData.js — 417 verified ACNH villagers from Nookipedia API
// All birthdays and personalities verified 2026-03-17

export const VILLAGERS = [
  // Alligators
  { name: "Alfonso", species: "Alligator", personality: "Lazy", birthday: "06-09" },
  { name: "Alli", species: "Alligator", personality: "Snooty", birthday: "11-08" },
  { name: "Boots", species: "Alligator", personality: "Jock", birthday: "08-07" },
  { name: "Del", species: "Alligator", personality: "Cranky", birthday: "05-27" },
  { name: "Drago", species: "Alligator", personality: "Lazy", birthday: "02-12" },
  { name: "Gayle", species: "Alligator", personality: "Normal", birthday: "05-17" },
  { name: "Roswell", species: "Alligator", personality: "Smug", birthday: "05-02" },
  { name: "Sly", species: "Alligator", personality: "Jock", birthday: "11-15" },

  // Anteaters
  { name: "Anabelle", species: "Anteater", personality: "Peppy", birthday: "02-16" },
  { name: "Annalisa", species: "Anteater", personality: "Normal", birthday: "02-06" },
  { name: "Antonio", species: "Anteater", personality: "Jock", birthday: "10-20" },
  { name: "Cyrano", species: "Anteater", personality: "Cranky", birthday: "03-09" },
  { name: "Olaf", species: "Anteater", personality: "Smug", birthday: "05-19" },
  { name: "Pango", species: "Anteater", personality: "Peppy", birthday: "11-09" },
  { name: "Snooty", species: "Anteater", personality: "Snooty", birthday: "10-24" },
  { name: "Zoe", species: "Anteater", personality: "Normal", birthday: "02-10" },

  // Bears
  { name: "Beardo", species: "Bear", personality: "Smug", birthday: "09-27" },
  { name: "Charlise", species: "Bear", personality: "Big sister", birthday: "04-17" },
  { name: "Chow", species: "Bear", personality: "Cranky", birthday: "07-22" },
  { name: "Curt", species: "Bear", personality: "Cranky", birthday: "07-01" },
  { name: "Grizzly", species: "Bear", personality: "Cranky", birthday: "07-31" },
  { name: "Groucho", species: "Bear", personality: "Cranky", birthday: "10-23" },
  { name: "Ike", species: "Bear", personality: "Cranky", birthday: "05-16" },
  { name: "Klaus", species: "Bear", personality: "Smug", birthday: "03-31" },
  { name: "Megan", species: "Bear", personality: "Normal", birthday: "03-13" },
  { name: "Nate", species: "Bear", personality: "Lazy", birthday: "08-16" },
  { name: "Paula", species: "Bear", personality: "Big sister", birthday: "03-22" },
  { name: "Pinky", species: "Bear", personality: "Peppy", birthday: "09-09" },
  { name: "Teddy", species: "Bear", personality: "Jock", birthday: "09-26" },
  { name: "Tutu", species: "Bear", personality: "Peppy", birthday: "09-15" },
  { name: "Ursala", species: "Bear", personality: "Big sister", birthday: "01-16" },

  // Bear cubs
  { name: "Barold", species: "Bear cub", personality: "Lazy", birthday: "03-02" },
  { name: "Bluebear", species: "Bear cub", personality: "Peppy", birthday: "06-24" },
  { name: "Cheri", species: "Bear cub", personality: "Peppy", birthday: "03-17" },
  { name: "Chester", species: "Bear cub", personality: "Lazy", birthday: "08-06" },
  { name: "Judy", species: "Bear cub", personality: "Snooty", birthday: "03-10" },
  { name: "June", species: "Bear cub", personality: "Normal", birthday: "05-21" },
  { name: "Kody", species: "Bear cub", personality: "Jock", birthday: "09-28" },
  { name: "Maple", species: "Bear cub", personality: "Normal", birthday: "06-15" },
  { name: "Marty", species: "Bear cub", personality: "Lazy", birthday: "04-16" },
  { name: "Murphy", species: "Bear cub", personality: "Cranky", birthday: "12-29" },
  { name: "Olive", species: "Bear cub", personality: "Normal", birthday: "07-12" },
  { name: "Pekoe", species: "Bear cub", personality: "Normal", birthday: "05-18" },
  { name: "Poncho", species: "Bear cub", personality: "Jock", birthday: "01-02" },
  { name: "Pudge", species: "Bear cub", personality: "Lazy", birthday: "06-11" },
  { name: "Stitches", species: "Bear cub", personality: "Lazy", birthday: "02-10" },
  { name: "Tammy", species: "Bear cub", personality: "Big sister", birthday: "06-23" },
  { name: "Vladimir", species: "Bear cub", personality: "Cranky", birthday: "08-02" },

  // Birds
  { name: "Ace", species: "Bird", personality: "Jock", birthday: "08-11" },
  { name: "Admiral", species: "Bird", personality: "Cranky", birthday: "01-27" },
  { name: "Anchovy", species: "Bird", personality: "Lazy", birthday: "03-04" },
  { name: "Jacob", species: "Bird", personality: "Lazy", birthday: "08-24" },
  { name: "Jacques", species: "Bird", personality: "Smug", birthday: "06-22" },
  { name: "Jay", species: "Bird", personality: "Jock", birthday: "07-17" },
  { name: "Jitters", species: "Bird", personality: "Jock", birthday: "02-02" },
  { name: "Lucha", species: "Bird", personality: "Smug", birthday: "12-12" },
  { name: "Midge", species: "Bird", personality: "Normal", birthday: "03-12" },
  { name: "Peck", species: "Bird", personality: "Jock", birthday: "07-25" },
  { name: "Piper", species: "Bird", personality: "Peppy", birthday: "04-18" },
  { name: "Robin", species: "Bird", personality: "Snooty", birthday: "12-04" },
  { name: "Sparro", species: "Bird", personality: "Jock", birthday: "11-20" },
  { name: "Tulin", species: "Bird", personality: "Jock", birthday: "03-03" },
  { name: "Twiggy", species: "Bird", personality: "Peppy", birthday: "07-13" },

  // Bulls
  { name: "Angus", species: "Bull", personality: "Cranky", birthday: "04-30" },
  { name: "Coach", species: "Bull", personality: "Jock", birthday: "04-29" },
  { name: "Rodeo", species: "Bull", personality: "Lazy", birthday: "10-29" },
  { name: "Stu", species: "Bull", personality: "Lazy", birthday: "04-20" },
  { name: "T-Bone", species: "Bull", personality: "Cranky", birthday: "05-20" },
  { name: "Vic", species: "Bull", personality: "Cranky", birthday: "12-29" },

  // Cats
  { name: "Ankha", species: "Cat", personality: "Snooty", birthday: "09-22" },
  { name: "Bob", species: "Cat", personality: "Lazy", birthday: "01-01" },
  { name: "Felicity", species: "Cat", personality: "Peppy", birthday: "03-30" },
  { name: "Kabuki", species: "Cat", personality: "Cranky", birthday: "11-29" },
  { name: "Katt", species: "Cat", personality: "Big sister", birthday: "04-27" },
  { name: "Kid Cat", species: "Cat", personality: "Jock", birthday: "08-01" },
  { name: "Kiki", species: "Cat", personality: "Normal", birthday: "10-08" },
  { name: "Kitty", species: "Cat", personality: "Snooty", birthday: "02-15" },
  { name: "Lolly", species: "Cat", personality: "Normal", birthday: "03-27" },
  { name: "Merry", species: "Cat", personality: "Peppy", birthday: "06-29" },
  { name: "Mitzi", species: "Cat", personality: "Normal", birthday: "09-25" },
  { name: "Moe", species: "Cat", personality: "Lazy", birthday: "01-12" },
  { name: "Monique", species: "Cat", personality: "Snooty", birthday: "09-30" },
  { name: "Olivia", species: "Cat", personality: "Snooty", birthday: "02-03" },
  { name: "Punchy", species: "Cat", personality: "Lazy", birthday: "04-11" },
  { name: "Purrl", species: "Cat", personality: "Snooty", birthday: "05-29" },
  { name: "Raymond", species: "Cat", personality: "Smug", birthday: "10-01" },
  { name: "Rosie", species: "Cat", personality: "Peppy", birthday: "02-27" },
  { name: "Rudy", species: "Cat", personality: "Jock", birthday: "12-20" },
  { name: "Stinky", species: "Cat", personality: "Jock", birthday: "08-17" },
  { name: "Tabby", species: "Cat", personality: "Peppy", birthday: "08-13" },
  { name: "Tangy", species: "Cat", personality: "Peppy", birthday: "06-17" },
  { name: "Tom", species: "Cat", personality: "Cranky", birthday: "12-10" },

  // Chickens
  { name: "Ava", species: "Chicken", personality: "Normal", birthday: "04-28" },
  { name: "Becky", species: "Chicken", personality: "Snooty", birthday: "12-09" },
  { name: "Benedict", species: "Chicken", personality: "Lazy", birthday: "10-10" },
  { name: "Broffina", species: "Chicken", personality: "Snooty", birthday: "10-24" },
  { name: "Egbert", species: "Chicken", personality: "Lazy", birthday: "10-14" },
  { name: "Goose", species: "Chicken", personality: "Jock", birthday: "10-04" },
  { name: "Ken", species: "Chicken", personality: "Smug", birthday: "12-23" },
  { name: "Knox", species: "Chicken", personality: "Cranky", birthday: "11-23" },
  { name: "Plucky", species: "Chicken", personality: "Big sister", birthday: "10-12" },

  // Cows
  { name: "Naomi", species: "Cow", personality: "Snooty", birthday: "02-28" },
  { name: "Norma", species: "Cow", personality: "Normal", birthday: "09-20" },
  { name: "Patty", species: "Cow", personality: "Peppy", birthday: "05-10" },
  { name: "Tipper", species: "Cow", personality: "Snooty", birthday: "08-25" },

  // Deers
  { name: "Bam", species: "Deer", personality: "Jock", birthday: "11-07" },
  { name: "Beau", species: "Deer", personality: "Lazy", birthday: "04-05" },
  { name: "Bruce", species: "Deer", personality: "Cranky", birthday: "05-26" },
  { name: "Chelsea", species: "Deer", personality: "Normal", birthday: "01-18" },
  { name: "Deirdre", species: "Deer", personality: "Big sister", birthday: "05-04" },
  { name: "Diana", species: "Deer", personality: "Snooty", birthday: "01-04" },
  { name: "Erik", species: "Deer", personality: "Lazy", birthday: "07-27" },
  { name: "Fauna", species: "Deer", personality: "Normal", birthday: "03-26" },
  { name: "Fuchsia", species: "Deer", personality: "Big sister", birthday: "09-19" },
  { name: "Lopez", species: "Deer", personality: "Smug", birthday: "08-20" },
  { name: "Mineru", species: "Deer", personality: "Snooty", birthday: "05-12" },
  { name: "Shino", species: "Deer", personality: "Peppy", birthday: "10-31" },
  { name: "Zell", species: "Deer", personality: "Smug", birthday: "06-07" },

  // Dogs
  { name: "Bea", species: "Dog", personality: "Normal", birthday: "10-15" },
  { name: "Benjamin", species: "Dog", personality: "Lazy", birthday: "08-03" },
  { name: "Biskit", species: "Dog", personality: "Lazy", birthday: "05-13" },
  { name: "Bones", species: "Dog", personality: "Lazy", birthday: "08-04" },
  { name: "Butch", species: "Dog", personality: "Cranky", birthday: "11-01" },
  { name: "Cherry", species: "Dog", personality: "Big sister", birthday: "05-11" },
  { name: "Cookie", species: "Dog", personality: "Peppy", birthday: "06-18" },
  { name: "Daisy", species: "Dog", personality: "Normal", birthday: "11-16" },
  { name: "Frett", species: "Dog", personality: "Cranky", birthday: "10-30" },
  { name: "Goldie", species: "Dog", personality: "Normal", birthday: "12-27" },
  { name: "Lucky", species: "Dog", personality: "Lazy", birthday: "11-04" },
  { name: "Mac", species: "Dog", personality: "Jock", birthday: "11-11" },
  { name: "Maddie", species: "Dog", personality: "Peppy", birthday: "01-11" },
  { name: "Marcel", species: "Dog", personality: "Lazy", birthday: "12-31" },
  { name: "Portia", species: "Dog", personality: "Snooty", birthday: "10-25" },
  { name: "Shep", species: "Dog", personality: "Smug", birthday: "11-24" },
  { name: "Walker", species: "Dog", personality: "Lazy", birthday: "06-10" },

  // Ducks
  { name: "Bill", species: "Duck", personality: "Jock", birthday: "02-01" },
  { name: "Deena", species: "Duck", personality: "Normal", birthday: "06-27" },
  { name: "Derwin", species: "Duck", personality: "Lazy", birthday: "05-25" },
  { name: "Drake", species: "Duck", personality: "Lazy", birthday: "06-25" },
  { name: "Freckles", species: "Duck", personality: "Peppy", birthday: "02-19" },
  { name: "Gloria", species: "Duck", personality: "Snooty", birthday: "08-12" },
  { name: "Joey", species: "Duck", personality: "Lazy", birthday: "01-03" },
  { name: "Ketchup", species: "Duck", personality: "Peppy", birthday: "07-27" },
  { name: "Maelle", species: "Duck", personality: "Snooty", birthday: "04-08" },
  { name: "Mallary", species: "Duck", personality: "Snooty", birthday: "11-17" },
  { name: "Miranda", species: "Duck", personality: "Snooty", birthday: "04-23" },
  { name: "Molly", species: "Duck", personality: "Normal", birthday: "03-07" },
  { name: "Pate", species: "Duck", personality: "Peppy", birthday: "02-23" },
  { name: "Pompom", species: "Duck", personality: "Peppy", birthday: "02-11" },
  { name: "Quillson", species: "Duck", personality: "Smug", birthday: "12-22" },
  { name: "Scoot", species: "Duck", personality: "Jock", birthday: "06-13" },
  { name: "Weber", species: "Duck", personality: "Lazy", birthday: "06-30" },

  // Eagles
  { name: "Amelia", species: "Eagle", personality: "Snooty", birthday: "11-19" },
  { name: "Apollo", species: "Eagle", personality: "Cranky", birthday: "07-04" },
  { name: "Avery", species: "Eagle", personality: "Cranky", birthday: "02-22" },
  { name: "Buzz", species: "Eagle", personality: "Cranky", birthday: "12-07" },
  { name: "Celia", species: "Eagle", personality: "Normal", birthday: "03-25" },
  { name: "Frank", species: "Eagle", personality: "Cranky", birthday: "07-30" },
  { name: "Keaton", species: "Eagle", personality: "Smug", birthday: "06-01" },
  { name: "Pierce", species: "Eagle", personality: "Jock", birthday: "01-08" },
  { name: "Quinn", species: "Eagle", personality: "Big sister", birthday: "01-20" },
  { name: "Sterling", species: "Eagle", personality: "Jock", birthday: "12-11" },

  // Elephants
  { name: "Axel", species: "Elephant", personality: "Jock", birthday: "03-23" },
  { name: "Big Top", species: "Elephant", personality: "Lazy", birthday: "10-03" },
  { name: "Chai", species: "Elephant", personality: "Peppy", birthday: "03-06" },
  { name: "Cyd", species: "Elephant", personality: "Cranky", birthday: "06-09" },
  { name: "Dizzy", species: "Elephant", personality: "Lazy", birthday: "07-14" },
  { name: "Ellie", species: "Elephant", personality: "Normal", birthday: "05-12" },
  { name: "Eloise", species: "Elephant", personality: "Snooty", birthday: "12-08" },
  { name: "Margie", species: "Elephant", personality: "Normal", birthday: "01-28" },
  { name: "Opal", species: "Elephant", personality: "Snooty", birthday: "01-20" },
  { name: "Paolo", species: "Elephant", personality: "Lazy", birthday: "05-05" },
  { name: "Tia", species: "Elephant", personality: "Normal", birthday: "11-18" },
  { name: "Tucker", species: "Elephant", personality: "Lazy", birthday: "09-07" },

  // Frogs
  { name: "Camofrog", species: "Frog", personality: "Cranky", birthday: "06-05" },
  { name: "Cousteau", species: "Frog", personality: "Jock", birthday: "12-17" },
  { name: "Croque", species: "Frog", personality: "Cranky", birthday: "07-18" },
  { name: "Diva", species: "Frog", personality: "Big sister", birthday: "10-02" },
  { name: "Drift", species: "Frog", personality: "Jock", birthday: "10-09" },
  { name: "Frobert", species: "Frog", personality: "Jock", birthday: "02-08" },
  { name: "Gigi", species: "Frog", personality: "Snooty", birthday: "08-11" },
  { name: "Henry", species: "Frog", personality: "Smug", birthday: "09-21" },
  { name: "Huck", species: "Frog", personality: "Smug", birthday: "07-09" },
  { name: "Jambette", species: "Frog", personality: "Normal", birthday: "10-27" },
  { name: "Jeremiah", species: "Frog", personality: "Lazy", birthday: "07-08" },
  { name: "Lily", species: "Frog", personality: "Normal", birthday: "02-04" },
  { name: "Prince", species: "Frog", personality: "Lazy", birthday: "07-21" },
  { name: "Puddles", species: "Frog", personality: "Peppy", birthday: "01-13" },
  { name: "Raddle", species: "Frog", personality: "Lazy", birthday: "06-06" },
  { name: "Ribbot", species: "Frog", personality: "Jock", birthday: "02-13" },
  { name: "Tad", species: "Frog", personality: "Jock", birthday: "08-03" },
  { name: "Wart Jr.", species: "Frog", personality: "Cranky", birthday: "08-21" },

  // Goats
  { name: "Billy", species: "Goat", personality: "Jock", birthday: "03-25" },
  { name: "Chevre", species: "Goat", personality: "Normal", birthday: "03-06" },
  { name: "Gruff", species: "Goat", personality: "Cranky", birthday: "08-29" },
  { name: "Kidd", species: "Goat", personality: "Smug", birthday: "06-28" },
  { name: "Nan", species: "Goat", personality: "Normal", birthday: "08-24" },
  { name: "Pashmina", species: "Goat", personality: "Big sister", birthday: "12-26" },
  { name: "Sherb", species: "Goat", personality: "Lazy", birthday: "01-18" },
  { name: "Velma", species: "Goat", personality: "Snooty", birthday: "01-14" },

  // Gorillas
  { name: "Al", species: "Gorilla", personality: "Lazy", birthday: "10-18" },
  { name: "Boone", species: "Gorilla", personality: "Jock", birthday: "09-12" },
  { name: "Boyd", species: "Gorilla", personality: "Cranky", birthday: "10-01" },
  { name: "Cesar", species: "Gorilla", personality: "Cranky", birthday: "09-06" },
  { name: "Hans", species: "Gorilla", personality: "Smug", birthday: "12-05" },
  { name: "Louie", species: "Gorilla", personality: "Jock", birthday: "03-26" },
  { name: "Peewee", species: "Gorilla", personality: "Cranky", birthday: "09-11" },
  { name: "Rilla", species: "Gorilla", personality: "Peppy", birthday: "11-01" },
  { name: "Rocket", species: "Gorilla", personality: "Big sister", birthday: "04-14" },
  { name: "Violet", species: "Gorilla", personality: "Snooty", birthday: "09-01" },

  // Hamsters
  { name: "Apple", species: "Hamster", personality: "Peppy", birthday: "09-24" },
  { name: "Clay", species: "Hamster", personality: "Lazy", birthday: "10-19" },
  { name: "Flurry", species: "Hamster", personality: "Normal", birthday: "01-30" },
  { name: "Graham", species: "Hamster", personality: "Smug", birthday: "06-20" },
  { name: "Hamlet", species: "Hamster", personality: "Jock", birthday: "05-30" },
  { name: "Hamphrey", species: "Hamster", personality: "Cranky", birthday: "02-25" },
  { name: "Marlo", species: "Hamster", personality: "Cranky", birthday: "06-26" },
  { name: "Rodney", species: "Hamster", personality: "Smug", birthday: "11-10" },
  { name: "Soleil", species: "Hamster", personality: "Snooty", birthday: "08-09" },

  // Hippos
  { name: "Bertha", species: "Hippo", personality: "Normal", birthday: "04-25" },
  { name: "Biff", species: "Hippo", personality: "Jock", birthday: "03-29" },
  { name: "Bitty", species: "Hippo", personality: "Snooty", birthday: "10-06" },
  { name: "Bubbles", species: "Hippo", personality: "Peppy", birthday: "09-18" },
  { name: "Harry", species: "Hippo", personality: "Cranky", birthday: "01-07" },
  { name: "Hippeux", species: "Hippo", personality: "Smug", birthday: "10-15" },
  { name: "Rocco", species: "Hippo", personality: "Cranky", birthday: "08-18" },

  // Horses
  { name: "Annalise", species: "Horse", personality: "Snooty", birthday: "12-02" },
  { name: "Buck", species: "Horse", personality: "Jock", birthday: "04-04" },
  { name: "Cleo", species: "Horse", personality: "Snooty", birthday: "02-09" },
  { name: "Clyde", species: "Horse", personality: "Lazy", birthday: "05-01" },
  { name: "Colton", species: "Horse", personality: "Smug", birthday: "05-22" },
  { name: "Ed", species: "Horse", personality: "Smug", birthday: "09-16" },
  { name: "Elmer", species: "Horse", personality: "Lazy", birthday: "10-05" },
  { name: "Julian", species: "Horse", personality: "Smug", birthday: "03-15" },
  { name: "Papi", species: "Horse", personality: "Lazy", birthday: "01-10" },
  { name: "Peaches", species: "Horse", personality: "Normal", birthday: "11-28" },
  { name: "Reneigh", species: "Horse", personality: "Big sister", birthday: "06-04" },
  { name: "Roscoe", species: "Horse", personality: "Cranky", birthday: "06-16" },
  { name: "Savannah", species: "Horse", personality: "Normal", birthday: "01-25" },
  { name: "Victoria", species: "Horse", personality: "Peppy", birthday: "07-11" },
  { name: "Winnie", species: "Horse", personality: "Peppy", birthday: "01-31" },

  // Kangaroos
  { name: "Astrid", species: "Kangaroo", personality: "Snooty", birthday: "09-08" },
  { name: "Carrie", species: "Kangaroo", personality: "Normal", birthday: "12-05" },
  { name: "Kitt", species: "Kangaroo", personality: "Normal", birthday: "10-11" },
  { name: "Marcie", species: "Kangaroo", personality: "Normal", birthday: "05-31" },
  { name: "Mathilda", species: "Kangaroo", personality: "Snooty", birthday: "11-12" },
  { name: "Rooney", species: "Kangaroo", personality: "Cranky", birthday: "12-01" },
  { name: "Sylvia", species: "Kangaroo", personality: "Big sister", birthday: "05-03" },
  { name: "Walt", species: "Kangaroo", personality: "Cranky", birthday: "04-24" },

  // Koalas
  { name: "Alice", species: "Koala", personality: "Normal", birthday: "08-19" },
  { name: "Canberra", species: "Koala", personality: "Big sister", birthday: "05-14" },
  { name: "Eugene", species: "Koala", personality: "Smug", birthday: "10-26" },
  { name: "Faith", species: "Koala", personality: "Big sister", birthday: "03-21" },
  { name: "Gonzo", species: "Koala", personality: "Cranky", birthday: "10-13" },
  { name: "Lyman", species: "Koala", personality: "Jock", birthday: "10-12" },
  { name: "Melba", species: "Koala", personality: "Normal", birthday: "04-12" },
  { name: "Ozzie", species: "Koala", personality: "Lazy", birthday: "05-07" },
  { name: "Sydney", species: "Koala", personality: "Normal", birthday: "06-21" },
  { name: "Yuka", species: "Koala", personality: "Snooty", birthday: "07-20" },

  // Lions
  { name: "Bud", species: "Lion", personality: "Jock", birthday: "08-08" },
  { name: "Elvis", species: "Lion", personality: "Cranky", birthday: "07-23" },
  { name: "Leopold", species: "Lion", personality: "Smug", birthday: "08-14" },
  { name: "Lionel", species: "Lion", personality: "Smug", birthday: "07-29" },
  { name: "Mott", species: "Lion", personality: "Jock", birthday: "07-10" },
  { name: "Rex", species: "Lion", personality: "Lazy", birthday: "07-24" },
  { name: "Rory", species: "Lion", personality: "Jock", birthday: "08-07" },

  // Monkeys
  { name: "Deli", species: "Monkey", personality: "Lazy", birthday: "05-24" },
  { name: "Elise", species: "Monkey", personality: "Snooty", birthday: "03-21" },
  { name: "Flip", species: "Monkey", personality: "Jock", birthday: "11-21" },
  { name: "Monty", species: "Monkey", personality: "Cranky", birthday: "12-07" },
  { name: "Nana", species: "Monkey", personality: "Normal", birthday: "08-23" },
  { name: "Shari", species: "Monkey", personality: "Big sister", birthday: "04-10" },
  { name: "Simon", species: "Monkey", personality: "Lazy", birthday: "01-19" },
  { name: "Tammi", species: "Monkey", personality: "Peppy", birthday: "04-02" },
  { name: "Tiansheng", species: "Monkey", personality: "Jock", birthday: "08-18" },

  // Mouses
  { name: "Anicotti", species: "Mouse", personality: "Peppy", birthday: "02-24" },
  { name: "Bella", species: "Mouse", personality: "Peppy", birthday: "12-28" },
  { name: "Bettina", species: "Mouse", personality: "Normal", birthday: "06-12" },
  { name: "Bree", species: "Mouse", personality: "Snooty", birthday: "07-07" },
  { name: "Broccolo", species: "Mouse", personality: "Lazy", birthday: "06-30" },
  { name: "Candi", species: "Mouse", personality: "Peppy", birthday: "04-13" },
  { name: "Chadder", species: "Mouse", personality: "Smug", birthday: "12-15" },
  { name: "Dora", species: "Mouse", personality: "Normal", birthday: "02-18" },
  { name: "Greta", species: "Mouse", personality: "Snooty", birthday: "09-05" },
  { name: "Limberg", species: "Mouse", personality: "Cranky", birthday: "10-17" },
  { name: "Moose", species: "Mouse", personality: "Jock", birthday: "09-13" },
  { name: "Penelope", species: "Mouse", personality: "Peppy", birthday: "02-05" },
  { name: "Petri", species: "Mouse", personality: "Snooty", birthday: "10-23" },
  { name: "Rizzo", species: "Mouse", personality: "Cranky", birthday: "01-17" },
  { name: "Rod", species: "Mouse", personality: "Jock", birthday: "08-14" },
  { name: "Samson", species: "Mouse", personality: "Jock", birthday: "07-05" },

  // Octopuss
  { name: "Cephalobot", species: "Octopus", personality: "Smug", birthday: "04-01" },
  { name: "Marina", species: "Octopus", personality: "Normal", birthday: "06-26" },
  { name: "Octavian", species: "Octopus", personality: "Cranky", birthday: "09-20" },
  { name: "Zucker", species: "Octopus", personality: "Lazy", birthday: "03-08" },

  // Ostrichs
  { name: "Blanche", species: "Ostrich", personality: "Snooty", birthday: "12-21" },
  { name: "Cranston", species: "Ostrich", personality: "Lazy", birthday: "09-23" },
  { name: "Flora", species: "Ostrich", personality: "Peppy", birthday: "02-09" },
  { name: "Gladys", species: "Ostrich", personality: "Normal", birthday: "01-15" },
  { name: "Julia", species: "Ostrich", personality: "Snooty", birthday: "07-31" },
  { name: "Phil", species: "Ostrich", personality: "Smug", birthday: "11-27" },
  { name: "Phoebe", species: "Ostrich", personality: "Big sister", birthday: "04-22" },
  { name: "Queenie", species: "Ostrich", personality: "Snooty", birthday: "11-13" },
  { name: "Rio", species: "Ostrich", personality: "Peppy", birthday: "09-10" },
  { name: "Sandy", species: "Ostrich", personality: "Normal", birthday: "10-21" },
  { name: "Sprocket", species: "Ostrich", personality: "Jock", birthday: "12-01" },

  // Penguins
  { name: "Aurora", species: "Penguin", personality: "Normal", birthday: "01-27" },
  { name: "Boomer", species: "Penguin", personality: "Lazy", birthday: "02-07" },
  { name: "Chabwick", species: "Penguin", personality: "Lazy", birthday: "12-24" },
  { name: "Cube", species: "Penguin", personality: "Lazy", birthday: "01-29" },
  { name: "Flo", species: "Penguin", personality: "Big sister", birthday: "09-02" },
  { name: "Friga", species: "Penguin", personality: "Snooty", birthday: "10-16" },
  { name: "Gwen", species: "Penguin", personality: "Snooty", birthday: "01-23" },
  { name: "Hopper", species: "Penguin", personality: "Cranky", birthday: "04-06" },
  { name: "Iggly", species: "Penguin", personality: "Jock", birthday: "11-02" },
  { name: "Puck", species: "Penguin", personality: "Lazy", birthday: "02-21" },
  { name: "Roald", species: "Penguin", personality: "Jock", birthday: "01-05" },
  { name: "Sprinkle", species: "Penguin", personality: "Peppy", birthday: "02-20" },
  { name: "Tex", species: "Penguin", personality: "Smug", birthday: "10-06" },
  { name: "Wade", species: "Penguin", personality: "Lazy", birthday: "10-30" },

  // Pigs
  { name: "Agnes", species: "Pig", personality: "Big sister", birthday: "04-21" },
  { name: "Boris", species: "Pig", personality: "Cranky", birthday: "11-06" },
  { name: "Chops", species: "Pig", personality: "Smug", birthday: "10-13" },
  { name: "Cobb", species: "Pig", personality: "Jock", birthday: "10-07" },
  { name: "Curly", species: "Pig", personality: "Jock", birthday: "07-26" },
  { name: "Gala", species: "Pig", personality: "Normal", birthday: "03-05" },
  { name: "Hugh", species: "Pig", personality: "Lazy", birthday: "12-30" },
  { name: "Kevin", species: "Pig", personality: "Jock", birthday: "04-26" },
  { name: "Lucy", species: "Pig", personality: "Normal", birthday: "06-02" },
  { name: "Maggie", species: "Pig", personality: "Normal", birthday: "09-03" },
  { name: "Pancetti", species: "Pig", personality: "Snooty", birthday: "11-14" },
  { name: "Peggy", species: "Pig", personality: "Peppy", birthday: "05-23" },
  { name: "Rasher", species: "Pig", personality: "Cranky", birthday: "04-07" },
  { name: "Spork", species: "Pig", personality: "Lazy", birthday: "09-03" },
  { name: "Truffles", species: "Pig", personality: "Peppy", birthday: "07-28" },

  // Rabbits
  { name: "Bonbon", species: "Rabbit", personality: "Peppy", birthday: "03-03" },
  { name: "Bunnie", species: "Rabbit", personality: "Peppy", birthday: "05-09" },
  { name: "Carmen", species: "Rabbit", personality: "Peppy", birthday: "01-06" },
  { name: "Chrissy", species: "Rabbit", personality: "Peppy", birthday: "08-28" },
  { name: "Claude", species: "Rabbit", personality: "Lazy", birthday: "12-03" },
  { name: "Coco", species: "Rabbit", personality: "Normal", birthday: "03-01" },
  { name: "Cole", species: "Rabbit", personality: "Lazy", birthday: "08-10" },
  { name: "Doc", species: "Rabbit", personality: "Lazy", birthday: "03-16" },
  { name: "Dotty", species: "Rabbit", personality: "Peppy", birthday: "03-14" },
  { name: "Francine", species: "Rabbit", personality: "Snooty", birthday: "01-22" },
  { name: "Gabi", species: "Rabbit", personality: "Peppy", birthday: "12-16" },
  { name: "Gaston", species: "Rabbit", personality: "Cranky", birthday: "10-28" },
  { name: "Genji", species: "Rabbit", personality: "Jock", birthday: "01-21" },
  { name: "Hopkins", species: "Rabbit", personality: "Lazy", birthday: "03-11" },
  { name: "Mira", species: "Rabbit", personality: "Big sister", birthday: "07-06" },
  { name: "O'Hare", species: "Rabbit", personality: "Smug", birthday: "07-24" },
  { name: "Pippy", species: "Rabbit", personality: "Peppy", birthday: "06-14" },
  { name: "Ruby", species: "Rabbit", personality: "Peppy", birthday: "12-25" },
  { name: "Sasha", species: "Rabbit", personality: "Lazy", birthday: "05-19" },
  { name: "Snake", species: "Rabbit", personality: "Jock", birthday: "11-03" },
  { name: "Tiffany", species: "Rabbit", personality: "Snooty", birthday: "01-09" },
  { name: "Toby", species: "Rabbit", personality: "Smug", birthday: "07-10" },

  // Rhinoceross
  { name: "Azalea", species: "Rhinoceros", personality: "Snooty", birthday: "12-18" },
  { name: "Hornsby", species: "Rhinoceros", personality: "Lazy", birthday: "03-20" },
  { name: "Merengue", species: "Rhinoceros", personality: "Normal", birthday: "03-19" },
  { name: "Renée", species: "Rhinoceros", personality: "Big sister", birthday: "05-28" },
  { name: "Rhonda", species: "Rhinoceros", personality: "Normal", birthday: "01-24" },
  { name: "Spike", species: "Rhinoceros", personality: "Cranky", birthday: "06-17" },
  { name: "Tank", species: "Rhinoceros", personality: "Jock", birthday: "05-06" },

  // Sheeps
  { name: "Baabara", species: "Sheep", personality: "Snooty", birthday: "03-28" },
  { name: "Cashmere", species: "Sheep", personality: "Snooty", birthday: "04-02" },
  { name: "Curlos", species: "Sheep", personality: "Smug", birthday: "05-08" },
  { name: "Dom", species: "Sheep", personality: "Jock", birthday: "03-18" },
  { name: "Étoile", species: "Sheep", personality: "Normal", birthday: "12-25" },
  { name: "Eunice", species: "Sheep", personality: "Normal", birthday: "04-03" },
  { name: "Frita", species: "Sheep", personality: "Big sister", birthday: "07-16" },
  { name: "Muffy", species: "Sheep", personality: "Big sister", birthday: "02-14" },
  { name: "Pietro", species: "Sheep", personality: "Smug", birthday: "04-19" },
  { name: "Stella", species: "Sheep", personality: "Normal", birthday: "04-09" },
  { name: "Timbra", species: "Sheep", personality: "Snooty", birthday: "10-21" },
  { name: "Vesta", species: "Sheep", personality: "Normal", birthday: "04-16" },
  { name: "Wendy", species: "Sheep", personality: "Peppy", birthday: "08-15" },
  { name: "Willow", species: "Sheep", personality: "Snooty", birthday: "11-26" },

  // Squirrels
  { name: "Agent S", species: "Squirrel", personality: "Peppy", birthday: "07-02" },
  { name: "Blaire", species: "Squirrel", personality: "Snooty", birthday: "07-03" },
  { name: "Cally", species: "Squirrel", personality: "Normal", birthday: "09-04" },
  { name: "Caroline", species: "Squirrel", personality: "Normal", birthday: "07-15" },
  { name: "Cece", species: "Squirrel", personality: "Peppy", birthday: "05-28" },
  { name: "Filbert", species: "Squirrel", personality: "Lazy", birthday: "06-03" },
  { name: "Hazel", species: "Squirrel", personality: "Big sister", birthday: "08-30" },
  { name: "Ione", species: "Squirrel", personality: "Normal", birthday: "09-11" },
  { name: "Marshal", species: "Squirrel", personality: "Smug", birthday: "09-29" },
  { name: "Mint", species: "Squirrel", personality: "Snooty", birthday: "05-02" },
  { name: "Nibbles", species: "Squirrel", personality: "Peppy", birthday: "07-19" },
  { name: "Peanut", species: "Squirrel", personality: "Peppy", birthday: "06-08" },
  { name: "Pecan", species: "Squirrel", personality: "Snooty", birthday: "09-10" },
  { name: "Poppy", species: "Squirrel", personality: "Normal", birthday: "08-05" },
  { name: "Ricky", species: "Squirrel", personality: "Cranky", birthday: "09-14" },
  { name: "Sally", species: "Squirrel", personality: "Normal", birthday: "06-19" },
  { name: "Sheldon", species: "Squirrel", personality: "Jock", birthday: "02-26" },
  { name: "Static", species: "Squirrel", personality: "Cranky", birthday: "07-09" },
  { name: "Sylvana", species: "Squirrel", personality: "Normal", birthday: "10-22" },
  { name: "Tasha", species: "Squirrel", personality: "Snooty", birthday: "11-30" },
  { name: "Viché", species: "Squirrel", personality: "Normal", birthday: "07-07" },

  // Tigers
  { name: "Bangle", species: "Tiger", personality: "Peppy", birthday: "08-27" },
  { name: "Bianca", species: "Tiger", personality: "Peppy", birthday: "12-13" },
  { name: "Claudia", species: "Tiger", personality: "Snooty", birthday: "11-22" },
  { name: "Leonardo", species: "Tiger", personality: "Jock", birthday: "05-15" },
  { name: "Rolf", species: "Tiger", personality: "Cranky", birthday: "08-22" },
  { name: "Rowan", species: "Tiger", personality: "Jock", birthday: "08-26" },
  { name: "Tybalt", species: "Tiger", personality: "Jock", birthday: "08-19" },

  // Wolfs
  { name: "Audie", species: "Wolf", personality: "Peppy", birthday: "08-31" },
  { name: "Chief", species: "Wolf", personality: "Cranky", birthday: "12-19" },
  { name: "Dobie", species: "Wolf", personality: "Cranky", birthday: "02-17" },
  { name: "Fang", species: "Wolf", personality: "Cranky", birthday: "12-18" },
  { name: "Freya", species: "Wolf", personality: "Snooty", birthday: "12-14" },
  { name: "Kyle", species: "Wolf", personality: "Smug", birthday: "12-06" },
  { name: "Lobo", species: "Wolf", personality: "Cranky", birthday: "11-05" },
  { name: "Skye", species: "Wolf", personality: "Normal", birthday: "03-24" },
  { name: "Vivian", species: "Wolf", personality: "Snooty", birthday: "01-26" },
  { name: "Whitney", species: "Wolf", personality: "Snooty", birthday: "09-17" },
  { name: "Wolfgang", species: "Wolf", personality: "Cranky", birthday: "11-25" }
];

// Pre-computed birthday calendar: month number -> array of { name, day }
export const BIRTHDAY_CALENDAR = {};
for (let m = 1; m <= 12; m++) BIRTHDAY_CALENDAR[m] = [];
VILLAGERS.forEach(v => {
  const [month, day] = v.birthday.split("-").map(Number);
  BIRTHDAY_CALENDAR[month].push({ name: v.name, date: day });
});
// Sort each month by day
Object.values(BIRTHDAY_CALENDAR).forEach(arr => arr.sort((a, b) => a.date - b.date));
