// src/modalThemes.js
// Pure data — no React, no side effects

export const MODAL_THEMES = {
  speechBubble: {
    name: 'ACNH Speech Bubble',
    backdrop: { background: 'rgba(0,0,0,0.5)' },
    container: {
      background: '#f5efe0',
      border: '3px solid #8b7355',
      borderRadius: '20px',
      boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
      padding: '20px 24px',
      textAlign: 'center',
      maxWidth: '360px',
      width: '90%',
      position: 'relative',
    },
    hasTail: true,
    tail: {
      width: '14px',
      height: '14px',
      background: '#f5efe0',
      border: '3px solid #8b7355',
      borderTop: 'none',
      borderLeft: 'none',
      transform: 'rotate(45deg)',
      position: 'absolute',
      bottom: '-9px',
      left: '50%',
      marginLeft: '-7px',
    },
    tailCover: {
      position: 'absolute',
      bottom: '0',
      left: '50%',
      marginLeft: '-10px',
      width: '20px',
      height: '5px',
      background: '#f5efe0',
    },
    accentBar: null,
    icon: '🍃',
    title: {
      fontFamily: "'Playfair Display', serif",
      fontWeight: 700,
      color: '#3d3428',
      fontSize: '16px',
      marginBottom: '6px',
    },
    message: {
      fontFamily: "'DM Sans', sans-serif",
      color: '#6b5e4a',
      fontSize: '13px',
      lineHeight: '1.5',
      marginBottom: '18px',
    },
    cancelBtn: {
      background: '#e8dcc8',
      border: '2px solid #8b7355',
      borderRadius: '24px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: '#5a4d3a',
      cursor: 'pointer',
    },
    confirmBtn: {
      background: '#5ec850',
      border: '2px solid #4aa840',
      borderRadius: '24px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
    },
    destructiveBtn: {
      background: '#e74c3c',
      border: '2px solid #c0392b',
      borderRadius: '24px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
    },
    alertBtn: {
      background: '#5ec850',
      border: '2px solid #4aa840',
      borderRadius: '24px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
    },
  },

  darkPortal: {
    name: 'Dark Portal',
    backdrop: { background: 'rgba(0,0,0,0.6)' },
    container: {
      background: 'rgba(12,28,14,0.98)',
      border: '1px solid rgba(94,200,80,0.25)',
      borderRadius: '14px',
      boxShadow: '0 0 30px rgba(94,200,80,0.08), 0 8px 32px rgba(0,0,0,0.5)',
      padding: '20px 24px',
      textAlign: 'center',
      maxWidth: '360px',
      width: '90%',
      position: 'relative',
    },
    hasTail: false,
    tail: null,
    tailCover: null,
    accentBar: null,
    icon: '🍃',
    title: {
      fontFamily: "'DM Sans', sans-serif",
      fontWeight: 600,
      color: '#c8e6c0',
      fontSize: '16px',
      marginBottom: '6px',
    },
    message: {
      fontFamily: "'DM Sans', sans-serif",
      color: '#5a7a50',
      fontSize: '13px',
      lineHeight: '1.5',
      marginBottom: '18px',
    },
    cancelBtn: {
      background: 'rgba(94,200,80,0.08)',
      border: '1px solid rgba(94,200,80,0.2)',
      borderRadius: '8px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: '#5a7a50',
      cursor: 'pointer',
    },
    confirmBtn: {
      background: '#5ec850',
      border: 'none',
      borderRadius: '8px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
    },
    destructiveBtn: {
      background: '#e74c3c',
      border: 'none',
      borderRadius: '8px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
    },
    alertBtn: {
      background: '#5ec850',
      border: 'none',
      borderRadius: '8px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
    },
  },

  hybrid: {
    name: 'Hybrid',
    backdrop: { background: 'rgba(0,0,0,0.55)' },
    container: {
      background: 'linear-gradient(135deg, rgba(12,28,14,0.98), rgba(20,40,22,0.98))',
      border: '2px solid rgba(94,200,80,0.3)',
      borderRadius: '18px',
      boxShadow: '0 0 40px rgba(94,200,80,0.1), 0 8px 32px rgba(0,0,0,0.5)',
      padding: '22px 24px',
      textAlign: 'center',
      maxWidth: '360px',
      width: '90%',
      position: 'relative',
    },
    hasTail: false,
    tail: null,
    tailCover: null,
    accentBar: {
      position: 'absolute',
      top: '-1px',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '60px',
      height: '3px',
      background: 'linear-gradient(90deg, transparent, #5ec850, transparent)',
      borderRadius: '2px',
    },
    icon: '🍃',
    title: {
      fontFamily: "'Playfair Display', serif",
      fontWeight: 700,
      color: '#c8e6c0',
      fontSize: '16px',
      marginBottom: '6px',
    },
    message: {
      fontFamily: "'DM Sans', sans-serif",
      color: '#7a9a70',
      fontSize: '13px',
      lineHeight: '1.5',
      marginBottom: '18px',
    },
    cancelBtn: {
      background: 'rgba(94,200,80,0.06)',
      border: '1px solid rgba(94,200,80,0.2)',
      borderRadius: '24px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: '#7a9a70',
      cursor: 'pointer',
    },
    confirmBtn: {
      background: 'linear-gradient(135deg, #5ec850, #4aa840)',
      border: 'none',
      borderRadius: '24px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
      boxShadow: '0 2px 8px rgba(94,200,80,0.3)',
    },
    destructiveBtn: {
      background: 'linear-gradient(135deg, #e74c3c, #c0392b)',
      border: 'none',
      borderRadius: '24px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
      boxShadow: '0 2px 8px rgba(231,76,60,0.3)',
    },
    alertBtn: {
      background: 'linear-gradient(135deg, #5ec850, #4aa840)',
      border: 'none',
      borderRadius: '24px',
      padding: '8px 24px',
      fontFamily: "'DM Sans', sans-serif",
      fontSize: '14px',
      color: 'white',
      fontWeight: 600,
      cursor: 'pointer',
      boxShadow: '0 2px 8px rgba(94,200,80,0.3)',
    },
  },
};

export const THEME_KEYS = Object.keys(MODAL_THEMES);
export const DEFAULT_THEME = 'hybrid';

// Shared animation keyframes — imported by both ConfirmModal and AlertModal
export const MODAL_ANIM_STYLE = `
@keyframes modalFadeIn { from { opacity:0; transform:scale(0.95); } to { opacity:1; transform:scale(1); } }
@keyframes modalFadeOut { from { opacity:1; transform:scale(1); } to { opacity:0; transform:scale(0.95); } }
@keyframes backdropFadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes backdropFadeOut { from { opacity:1; } to { opacity:0; } }
`;
